version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: junta_tribo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - junta-tribo-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - junta-tribo-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - junta-tribo-network

volumes:
  postgres_data:
  redis_data:

networks:
  junta-tribo-network:
    driver: bridge
